package main.seven;

//Generated by Selenium IDE

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class GridBefore {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@BeforeTest
public void setUp() throws MalformedURLException {
 driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.chrome());
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();
}
@AfterTest
public void tearDown() {
 driver.quit();
}
@Test
public void SomeCheck() {
 driver.get("https://www.booking.com/index.ru.html");
 driver.manage().window().setSize(new Dimension(1382, 744));
 driver.findElement(By.id("ss")).click();
 driver.switchTo().frame(0);
 driver.findElement(By.id("username")).sendKeys("dclind@mail.ru");
 driver.findElement(By.id("hidden-password")).sendKeys("123456789");
 driver.switchTo().defaultContent();
 driver.findElement(By.id("ss")).sendKeys("דמא");
 driver.findElement(By.cssSelector(".sb-autocomplete__item-with_photo:nth-child(1) > span:nth-child(2)")).click();
 driver.findElement(By.cssSelector(".bui-calendar__wrapper:nth-child(1) .bui-calendar__row:nth-child(3) > .bui-calendar__date:nth-child(1) > span > span")).click();
 driver.findElement(By.cssSelector(".bui-calendar__wrapper:nth-child(1) .bui-calendar__row:nth-child(3) > .bui-calendar__date:nth-child(7) > span > span")).click();
 driver.findElement(By.id("xp__guests__toggle")).click();
 driver.findElement(By.cssSelector(".sb-group__field-adults .bui-stepper__subtract-button")).click();
 driver.findElement(By.id("group_adults")).sendKeys("1");
 driver.findElement(By.cssSelector(".xp__guests__count > span:nth-child(2) > span")).click();
 driver.findElement(By.id("xp__guests__toggle")).click();
 driver.findElement(By.cssSelector(".sb-searchbox__button > span:nth-child(1)")).click();
 {
   WebElement element = driver.findElement(By.cssSelector(".bui-carousel__item:nth-child(3) .bui-card__title"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element).perform();
 }
 {
   WebElement element = driver.findElement(By.tagName("body"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element, 0, 0).perform();
 }
}
}
