package main.seven;


//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.BeforeTest;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;


public class IDEtest {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() throws MalformedURLException {
 driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.chrome());
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
 driver.quit();
}
@Test
public void testNameLenta() {
 driver.get("https://lenta.ru/");
 driver.manage().window().setSize(new Dimension(1382, 744));
 {
   WebElement element = driver.findElement(By.linkText("Россия"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element).perform();
 }
 driver.findElement(By.linkText("Россия")).click();
 js.executeScript("window.scrollTo(0,3800)");
 {
   WebElement element = driver.findElement(By.cssSelector(".b-longgrid-column:nth-child(3) > .item:nth-child(2) > .titles span"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element).perform();
 }
 {
   WebElement element = driver.findElement(By.tagName("body"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element, 0, 0).perform();
 }
 js.executeScript("window.scrollTo(0,4024)");
 js.executeScript("window.scrollTo(0,4074)");
 js.executeScript("window.scrollTo(0,0)");
 driver.findElement(By.linkText("Всё о коронавирусе")).click();
}
}

